# Generated by Django 4.0.6 on 2022-07-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='title',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(max_length=50),
        ),
    ]
