# Generated by Django 4.0.6 on 2022-07-28 15:41

from django.db import migrations, models
import django.utils.timezone
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_headertitle_remove_candidate_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='know_more',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situationreport',
            name='brief_description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='situationreport',
            name='video',
            field=models.FileField(upload_to='report_video/%Y/%m/%d/', validators=[report.models.validate_is_mp4, report.models.validate_file_size]),
        ),
    ]
