# Generated by Django 4.0.6 on 2022-07-29 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0004_situationreport_dislikes_situationreport_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video', to=settings.AUTH_USER_MODEL),
        ),
    ]
