# Generated by Django 4.0.6 on 2022-07-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_situationreport_likes_viewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcount',
            name='ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='session',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
