# Generated by Django 4.0.6 on 2022-08-01 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_viewcount_ip_address_alter_viewcount_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationreport',
            name='title',
            field=models.CharField(default='No Title', max_length=75),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='View_counts', to='report.situationreport'),
        ),
    ]
