# Generated by Django 4.0.6 on 2022-08-01 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_situationreport_title_alter_viewcount_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='situationreport',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.state'),
        ),
    ]
