# Generated by Django 4.0.6 on 2022-08-03 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0011_alter_state_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationreport',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
