# Generated by Django 4.0.6 on 2022-09-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_situationreport_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationreport',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
